-- Content distribution Analysis :-

/* Problem 1 : Find the overall split between TV shows and Movies on netflix, and find the percentage each of them makes up of total volume of content(including both tv shows and movies) on netflix :-
   - For this we will find the Group-wise result of count of both categories in the type column(i.e show type).
   - Then we will find the percentage the count of that show_type makes up to the count of total content in netflix. 
*/
SELECT
    type,
    COUNT(*) AS content_type_count -- will find the count of all the rows belonging to that category/group of type(content_type).
FROM
    netflix
GROUP BY -- grouping the result by the show type, so that we can get the aggregated result of count of each show type separately.
    type;

/* Problem 2 : Find the content-type-wise breakdown of all contents and what percentages do each of these categories make up of the entire content count mentioned in the netflix data? :
   - Here we will first find the mention the 'type' column inside of the SELECT statement, and also mntion that in the GROUP BY clause as well, so that we can get the aggregated result of content_count represented by COUNT(*) which will retrieve the count of all the rows/contents for each 'type' column's categories mentioned in the result-set.
   - Then the percentage that each of these content-type and their content_count make up of the total of all the content count of the netflix data will be displayed. For this we will mention COUNT(*) which will find the content_count of all the individual rows/contents from the netflix table belonging to each of the categories of 'type' column mentioned in the result-set, and then we divide it with the sum of all the content counts in the netflix data which we will find out using the SUM(COUNT(*)) OVER() , where the innner aggregation of COUNT(*) will basically be w.r.t the 'type' column's categories mentioned in the and hence will display the content-type-category-wise distribution of content_count for each of the content_types corresponding to their types in imaginary result-set, then the outer aggregation of SUM(...) OVER() will ensure that we get the sum of all the content counts of all the individual conent-type-categories because of the presence of OVER(), and since nothing is mentioned is inside of the over function , it will assume that the wndow frame of that particular outer aggregation of SUM will include all the rows from UNBOUNDED PRECEEDING AND UNBOUNDED FOLLOWING, hence the sum of the content_count of all the individual rows from the result-set i.e the sum of content_count for both the categories in 'type' column will be calculated giving us the total content count of netflix data, and then we will multiply it with 100 to get the overall percentage value of what percentage does that content-type category's content_count makes up of the total content count in netflix data.
   - Finally we will order the result in descending order of their content_count in the ORDER BY clause, so that in the result-set the content-types in the 'type' column with the most amount of content_count will be displayed at the very top along with the percentages that the content count of each of these categories makes up of the total content_count of the entire netflix data.
*/
SELECT
    type,
    COUNT(*) AS content_count, -- will find the count of all then rows/contents from netflix table, whose content-type belongs to the categories mentioned in the result-set
    (COUNT(*)/(SUM(COUNT(*)) OVER()) * 100) AS type_percentage_of_total_content -- will find the percentage of each content-type category makes up of the total content count in netflix, by dividing the count of content of that category of content-type with the sum of total count of all the individual categories in the 'type' column in netflix(since there are 2 types in type column , the sum of all the content_counts in these two content-type categories will give us the total of all content_count mentioned in netflix table). Here the first COUNT(*) is GROUPED on the basis of 'type' column as mentioned in the GROUP BY sub clause hence will give the content_count of each particular content-type category mentioned in the result set corresponding to them, and the second COUNT(*) mentioned to the left side of '/'(inside of the outer aggregation of SUM(...) OVER()) is grouped on the basis of 'type' column aswell, hence will show the type-wise content_count of each category mentioned in the type column of the netflix data corresponding to their types, the outter aggregation of SUM(...) OVER() mentioned on top of the second COUNT(*) will find the sum of all the content_counts of each of the categories mentioned in the type column of the netflix data, since the window function here because of the presence of OVER() will assume that it includes the window frame including all rows from unbounded preceeding and unbounded following , hence taking the sum of all the content_counts for all the rows mentioned in the result-set i.e the sum of content_counts of both these content-types(from the 'type' column's categories) giving us the total of all the content counts inside of the netflix data or the total content count of netflix data. So the overall expression says type_category's_content_count/sum_of_all_content_counts_in_netflix_data * 100, giving us the percentage value of what that content-type category's content_count makes up of the total content count in netflix data.
FROM -- retreiving the count of all the contents i.e individual rows from the netflix table which contains the netflix data, for showing the content_count of each of these content-type categories mentioned in the 'type' column of the netflix data, and also showing what percentage does the content_count of each of these make up of the total content_count of the entire netflix data.
    netflix
GROUP BY -- grouping the result on the basis of content-type category mentioned in the 'type' column of netflix data, so that we can get the aggregated result of content_count and percentage of total content for each content-type category separately.
    type
ORDER BY
    content_count DESC; -- ordering the result in descending order of content_count, so that we can see the content-type category with highest content count at the top of the result set.