-- 6_rating_distribution :-

/* Problem 13 : What is the overall rating distribution across Netflix's catalog, and what percentage of content does each rating hold? :-
   - For this we will call out the 'rating' column from the netflix table, and also mention that in GROUP BY clause, since its on the basis of each of the (categories in) ratings we are trying to find the content_count corresponding to it.
   - Then we will mention COUNT(*) which will find the count of all the rows from netflix table which belong to that particular rating, this will be done for all the ratings present in netflix data since the result is grouped by ratings column as mentioned in GROUP BY clause.
   - We will also find the percentage value that the content_count of that particular rating makes up of the total content there in netflix data. Here in the second part of the formula(after the '/') the inner aggregation of COUNT(*) will take place w.r.t ratings column mentioned in GROUP BY clause, hence will return the count of that particular rating and similarly all ratings-wise content_count, whereas the outter aggregation of SUM(...) OVER() will find the SUM of all the count of all the individual ratings over the entire result-set and this value of overall sum will be divided by the previously found value of count of content(mentioned before '/') for a particular rating, then this value will be multiplied by 100 to get the percentage value of the content of that particular rating to the overall content in netflix data.
   - In the WHERE clause we will filter out the rows which have their rating as '**Unknown**', as we are not interested in finding the count and percentage value of content for this particular rating, hence we will only consider the rows which have the value of rating column other than '**Unknown**'.
   - Finally we will ensure to display the result in descending order of content_count, to find the most frequent ratings at the top. 
*/
SELECT
    rating,
    COUNT(*) AS content_count, -- will find the count of all the rows from netflix table which belong to that particular rating, this will be done for all the ratings present in netflix data and the result will be grouped by ratings column as mentioned in GROUP BY clause.
    (COUNT(*)/SUM(COUNT(*)) OVER() * 100) AS percentage_of_rating_to_overall -- this will ensure to find the percentage value that the content_count of that particular rating makes up of the total content there in netflix data. Here in the second part of the formula(after the '/') the inner aggregation of COUNT(*) will take place w.r.t ratings column mentioned in GROUP BY clause, hence will return the count of that particular rating and similarly all ratings-wise content_count, in the current row of the result-set, whereas the outter aggregation of SUM(...) OVER() will find the SUM of all the count of all the individual ratings over the entire result-set and this value of overall sum will be divided by the previously found value of count of content(mentioned before '/') for a particular rating, then this value will be multiplied by 100 to get the percentage value of the content of that particular rating to the overall content in netflix data.
FROM
    netflix
WHERE -- this will ensure to filter out the rows which have their rating as '**Unknown**', as we are not interested in finding the count and percentage value of content for this particular rating, hence we will only consider the rows which have the value of rating column other than '**Unknown**'.
    rating != '**Unknown**'
GROUP BY -- this will ensure to group the result-set by ratings column, hence we will get the count of content for each individual rating and also the percentage value of that particular rating to the overall content in netflix data.
    rating
ORDER BY
    content_count DESC;

/* Problem 14 : How is content distributed across audience categories (Kids / Teens / Adults / Unclassified), and what percentage does each category hold? :-
   - For this we will first create a CTE called audience_category where-in we will create an entity named 'rating_by_audience' which will categorize the ratings into 4 categories(Kids, Kids(7+), Teens & Adults for known ratings) as mentioned in the CASE statement and if any rating does not fall into any of these 4 categories then it will be categorized as 'Unclassified'.
   - Then we will mention COUNT(*) which will find the count of all the rows from netflix table which belong to that particular rating_by_audience(based on its rating column, i.e in which rating_by_audience category does the rating of that row from original netflix data fall in, corresponding to those categories in rating_by_audience they will be counted), this will be done for all the rating_by_audience categories present in netflix data and the result will be grouped by rating_by_audience column as mentioned in GROUP BY clause.
   - Then in the main query we will call out the rating_by_audience column from the CTE created above, and also the content_count column which we have created in the CTE, and then we will find the percentage value that the content_count of that particular rating_by_audience category makes up of the total content there in netflix data. Here in the second part of the formula(after the '/') the SUM(content_count) OVER() will find the SUM of all the content_count values(of each of the rating_by_audience) over the entire result-set(i.e all rating_by_audience's combined SUN of content count) and this value of overall sum will be divided with the previously found value of content_count(mentioned before '/', i.e the content_count of that particular rating_by_audience's category) for a particular rating_by_audience, then this value will be multiplied by 100 to get the percentage value of the content of that particular rating_by_audience to the overall content in netflix data.
   - Finally we will ensure to display the result in descending order of content_count, to find the most frequent rating_by_audience categories at the top.
*/
WITH audience_category AS( -- This CTE will display the content count for each of the rating_by_audience category, where the rating_by_audience category is created by categorizing the ratings into 4 categories(Kids, Kids(7+), Teens & Adults for known ratings) as mentioned in the CASE statement and if any rating does not fall into any of these 4 categories then it will be categorized as 'Unclassified'.
SELECT
    CASE --  will ensure to create an entity named rating_by_audience which will categorize the ratings into 4 categories as mentioned in the CASE statement and if any rating does not fall into any of these 4 categories then it will be categorized as 'Unclassified'.
        WHEN rating IN ('G', 'TV-Y', 'TV-G') THEN 'Kids'
        WHEN rating IN ('TV-Y7', 'TV-Y7-FV', 'PG', 'TV-PG') THEN 'Kids (7+)'
        WHEN rating IN ('PG-13', 'TV-14') THEN 'Teens'
        WHEN rating IN ('R', 'NC-17', 'TV-MA') THEN 'Adults'
        ELSE 'Unclassified'
    END AS rating_by_audience,
    COUNT(*) AS content_count -- Since the overall result is grouped by the rating_by_audience column mentioned above, hence this will find the count of all the rows from netflix table which belong to that particular rating_by_audience(based on its rating column, i.e in which rating_by_category does the rating of that row from original netflix row fall in), this will be done for all the rating_by_audience categories present in netflix data and the result will be grouped by rating_by_audience column as mentioned in GROUP BY clause.
FROM
    netflix
GROUP BY -- this will ensure to group the result-set by rating_by_audience column, hence we will get the count of content for each individual rating_by_audience category and also the percentage value of that particular rating_by_audience category to the overall content in netflix data.
    rating_by_audience
)
SELECT -- Main query will call out the rating_by_audience column from the CTE created above, and also the content_count column which we have created in the CTE, and then we will find the percentage value that the content_count of that particular rating_by_audience category makes up of the total content there in netflix data. Here in the second part of the formula(after the '/') the SUM(content_count) OVER() will find the SUM of all the content_count values(of each of the rating_by_audience) over the entire result-set i.e all rating_by_audience's combined SUN of content count, and this value of overall sum will be divided with the previously found value of content_count(mentioned before '/', i.e the content_count of that particular rating_by_audience's category) for a particular rating_by_audience, then this value will be multiplied by 100 to get the percentage value of the content of that particular rating_by_audience to the overall content in netflix data.
    rating_by_audience,
    content_count,
    (content_count/(SUM(content_count) OVER()) * 100) AS percentage_of_rating_category -- will find the % the content_count of the rating_by_audience makes up to the total content count of the data. Here in the second part of the formula(after the '/') the SUM(content_count) OVER() will find the SUM of all the content_count values over the entire result-set(i.e f all rating_by_audience combined) and this value of overall sum will be divided with the previously found value of content_count for a particular rating_by_audience, then this value will be multiplied by 100 to get the percentage value of the content of that particular rating_by_audience to the overall content in netflix data.
FROM
    audience_category
ORDER BY
    content_count DESC;

/* Problem 15 : For each audience category, what is the Movies vs TV Shows breakdown? :- 
   - For this we will create a CTE called audience_category, where-in we will create an entity named 'rating_by_audience' which will categorize the ratings into 4 categories(Kids, Kids(7+), Teens, Adults & Unclassified[for unknown ratings]) as mentioned in the CASE statement. Along with this we will also find the content_count for each of the rating_by_audience category, and also find the count of content for each content type(Movie & TV Show) for each of the rating_by_audience category using CASE statements inside COUNT() aggregation function.
   - To get a rating_by_audience-wise breakdown, we will mention the rating_by_audience in GROUP BY clause, hence we will get the count of content of COUNT(*) which will count the individual rows belonging to each of the rating_by_audience categories.
   - We will then find the count of content for each content type(Movie & TV Show) for each of the rating_by_audience category using CASE statements inside COUNT() aggregation function, where all the rows from the netflix data(corresponding to that rating_by_audience) which is of the content_type of 'Movie' will be assigned 1 and any other content type(i.e 'TV Show') will by default be assigned NULL since no ELSE statement is mentioned in the CASE, then the outter aggregation function of COUNT() will ensure to count all those values from the imaginary new entity(assigned values using CASE) whose value has been assigned 1(for movie content-type) will be counted ignoring the NULL values(i.e the TV show content-type), similarly for TV show content type as well.
   - In the main query we will find the percentage value that each of the movie_count and tv_show_cunt makes up of the entire content_count of that rating_by_audience. For this in the first part of the formula we will mention content_count(of each of the rating_by_category) then divide it by(mentioned after '/') count of content for the entire rating_by_category which we will find out using the formula mentioned (i.e movie_count :: decimal / content_count[for the rating_by_category]) to find the percentage that the movies make up to the total content count of that year. Similarly we will also find the percentage of tv_show_count. Finally we will order the resulting result in descending order of their content_count, to display the most freequent rating_by_categories on the top of the list.
*/
WITH audience_category AS(
SELECT
    CASE --  will ensure to create an entity named rating_by_audience which will categorize the ratings into 4 categories as mentioned in the CASE statement and if any rating does not fall into any of these 4 categories then it will be categorized as 'Unclassified'.
        WHEN rating IN ('G', 'TV-Y', 'TV-G') THEN 'Kids'
        WHEN rating IN ('TV-Y7', 'TV-Y7-FV', 'PG', 'TV-PG') THEN 'Kids (7+)'
        WHEN rating IN ('PG-13', 'TV-14') THEN 'Teens'
        WHEN rating IN ('R', 'NC-17', 'TV-MA') THEN 'Adults'
        ELSE 'Unclassified'
    END AS rating_by_audience,
    COUNT(*) AS content_count, -- Since the overall result is grouped by the rating_by_audience column mentioned above, hence this will find the count of all the rows from netflix table which belong to that particular rating_by_audience(based on its rating column, i.e in which rating_by_category does the rating of that row from original netflix row fall in), this will be done for all the rating_by_audience categories present in netflix data and the result will be grouped by rating_by_audience column as mentioned in GROUP BY clause.
    COUNT(CASE WHEN type = 'Movie' THEN 1 END) AS movie_count, -- Will basicaly assign value using CASE Statements, where all the rows from the netflix data(corresponding to that rating_by_audience) which is of the content_type of 'Movie' will be assigned 1 and any other content type(i.e 'TV Show') will by default be assigned NULL since no ELSE statement is mentioned, then the outter aggregation function of COUNT() will ensure to count all those values from the imaginary new entity(assigned values using CASE) whose value has been assigned 1(for movie content-type) will be counted ignoring the NULL values(i.e the TV show content-type).
    COUNT(CASE WHEN type = 'TV Show' THEN 1 END) AS tv_show_count -- Will basicaly assign value using CASE Statements, where all the rows from the netflix data(corresponding to that rating_by_audience) which is of the content_type of 'TV Show' will be assigned 1 and any other content type(i.e 'Movie') will by default be assigned NULL since no ELSE statement is mentioned, then the outter aggregation function of COUNT() will ensure to count all those values from the imaginary new entity(assigned values using CASE) whose value has been assigned 1(for TV show content-type) will be counted ignoring the NULL values(i.e the Movie content-type).
FROM
    netflix
GROUP BY -- this will ensure to group the result-set by rating_by_audience column, hence we will get the count of content for each individual rating_by_audience category and also the percentage value of that particular rating_by_audience category to the overall content in netflix data.
    rating_by_audience
)
SELECT
    rating_by_audience,
    content_count,
    movie_count,
    tv_show_count,
    ((movie_count::decimal/content_count) * 100) AS percentage_movie_count, -- to find the percentage of movie content count out of the total content count for each country, we can divide the movie_count by the content_count and then multiply by 100 to get the percentage value. We should also cast movie_count to numeric data type to ensure that we get a decimal value for the percentage calculation instead of an integer division result.(Since both movie_count and content_count are of integer data type, hence if we do not cast any of these to numeric data type then the division will be treated as integer division and we will get an integer result, i.e ignoring the decimal part of the result of movie_count/content_count, which will lead to us getting the result as 0 since movie_count/content_count is gonna be less than 1 for all the rows of the result-set, hence we will get 0 for all the rows in percentage_movie_count column, which is not what we want, we want to get the actual percentage value with decimal part as well, hence we will cast movie_count to numeric data type to ensure that we get a decimal value for the percentage calculation instead of an integer division result).
    ((tv_show_count::decimal/content_count) * 100) AS percentage_tv_show_count -- to find the percentage of TV show content count out of the total content count for each country, we can divide the tv_show_count by the content_count and then multiply by 100 to get the percentage value. We should also cast tv_show_count to numeric data type to ensure that we get a decimal value for the percentage calculation instead of an integer division result.(Since both tv_show_count and content_count are of integer data type, hence if we do not cast any of these to numeric data type then the division will be treated as integer division and we will get an integer result, i.e ignoring the decimal part of the result of tv_show_count/content_count, which will lead to us getting the result as 0 since tv_show_count/content_count is gonna be less than 1 for all the rows of the result-set, hence we will get 0 for all the rows in percentage_tv_show_count column, which is not what we want, we want to get the actual percentage value with decimal part as well, hence we will cast tv_show_count to numeric data type to ensure that we get a decimal value for the percentage calculation instead of an integer division result).
FROM
    audience_category
ORDER BY -- will ensure to display the result in descending order of content_count, to find the rating_by_audience categories with most content_count at the top.
    content_count DESC;